import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono,Rubik_Dirt} from "next/font/google";
import Header from '../components/Header.tsx';
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const rubik = Rubik_Dirt({
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jetbrains.className}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
