import type { Metadata } from "next";
import "./globals.css";
import { quanticoFont } from './fonts';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='antialiased bg-(--background) w-full h-full'>
        <div className='w-full h-[10%] text-(--foreground) p-[26px] flex justify-around items-center absolute'>
        <a className={`border  border-white border-solid p-[4px] self-center justify-center flex rounded-[10px] absolute z-[1] ${quanticoFont.className}`}>JumpStart</a>           
                </div>
        {children}


      </body>
    </html>
  );
}
